<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="CoolCakeCook2\localization\eng\**" />
    <EmbeddedResource Remove="CoolCakeCook2\localization\eng\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include=".godot\mono\metadata\ide_messaging_meta.txt" />
    <Content Include=".godot\mono\temp\bin\ExportRelease\win-x64\CoolCakeCook2.deps.json" />
    <Content Include=".godot\mono\temp\bin\ExportRelease\win-x64\CoolCakeCook2.runtimeconfig.json" />
    <Content Include=".godot\mono\temp\obj\CoolCakeCook2.csproj.nuget.dgspec.json" />
    <Content Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.csproj.FileListAbsolute.txt" />
    <Content Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.sourcelink.json" />
    <Content Include=".godot\mono\temp\obj\ExportRelease\win-x64\PublishOutputs.4e8d8e4e82.txt" />
    <Content Include=".godot\mono\temp\obj\ExportRelease\win-x64\PublishOutputs.5e59feb539.txt" />
    <Content Include=".godot\mono\temp\obj\ExportRelease\win-x64\PublishOutputs.85f7d35d4e.txt" />
    <Content Include=".godot\mono\temp\obj\ExportRelease\win-x64\PublishOutputs.aca1caa2af.txt" />
    <Content Include=".godot\mono\temp\obj\ExportRelease\win-x64\PublishOutputs.e59b029a9c.txt" />
    <Content Include=".godot\mono\temp\obj\project.assets.json" />
    <Content Include="CoolCakeCook2.json" />
    <Content Include="CoolCakeCook2\images\card_portraits\big\pancake.png" />
    <Content Include="CoolCakeCook2\images\card_portraits\big\pat.png" />
    <Content Include="CoolCakeCook2\images\card_portraits\pancake.png" />
    <Content Include="CoolCakeCook2\images\card_portraits\pat.png" />
    <Content Include="CoolCakeCook2\images\charui\big_energy.png" />
    <Content Include="CoolCakeCook2\images\charui\character_icon_char_name.png" />
    <Content Include="CoolCakeCook2\images\charui\char_select_char_name.png" />
    <Content Include="CoolCakeCook2\images\charui\char_select_char_name_locked.png" />
    <Content Include="CoolCakeCook2\images\charui\map_marker_char_name.png" />
    <Content Include="CoolCakeCook2\images\charui\text_energy.png" />
    <Content Include="CoolCakeCook2\images\powers\big\power.png" />
    <Content Include="CoolCakeCook2\images\powers\power.png" />
    <Content Include="CoolCakeCook2\images\relics\big\relic.png" />
    <Content Include="CoolCakeCook2\images\relics\relic.png" />
    <Content Include="CoolCakeCook2\images\relics\relic_outline.png" />
    <Content Include="CoolCakeCook2\mod_image.png" />
    <Content Include="localization\zhs\cards.json" />
    <Content Include="localization\zhs\characters.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="0.1.9" />
    <AdditionalFiles Include="localization/**/*.json" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include=".godot\mono\temp\obj\Debug\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
    <Compile Include=".godot\mono\temp\obj\Debug\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs" />
    <Compile Include=".godot\mono\temp\obj\Debug\CoolCakeCook2.AssemblyInfo.cs" />
    <Compile Include=".godot\mono\temp\obj\Debug\CoolCakeCook2.GlobalUsings.g.cs" />
    <Compile Include=".godot\mono\temp\obj\ExportRelease\win-x64\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs" />
    <Compile Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.AssemblyInfo.cs" />
    <Compile Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.GlobalUsings.g.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include=".gitattributes" />
    <None Include=".gitignore" />
    <None Include=".godot\.gdignore" />
    <None Include=".godot\editor\ancients.json-folding-2e80fe9fe4d72b9686d5836dff5dfe1d.cfg" />
    <None Include=".godot\editor\cards.json-folding-8e0eb62065fd9bc6e65d29532d21dacf.cfg" />
    <None Include=".godot\editor\characters.json-folding-490d2aa3aecd3413ccd99e58861f06dc.cfg" />
    <None Include=".godot\editor\editor_layout.cfg" />
    <None Include=".godot\editor\editor_script_doc_cache.res-folding-a7de57390d6e786984ca20c70a831128.cfg" />
    <None Include=".godot\editor\favorites" />
    <None Include=".godot\editor\favorite_properties" />
    <None Include=".godot\editor\filesystem_cache10" />
    <None Include=".godot\editor\filesystem_update4" />
    <None Include=".godot\editor\Pancake.cs-folding-3ae3ce225507b339d5788e5eba3c8fd9.cfg" />
    <None Include=".godot\editor\Pat.cs-folding-4749a04c93dac8c8326a919cf2be2cad.cfg" />
    <None Include=".godot\editor\Pat.cs-folding-4f6c1fcfa9a09b58d26ff49c15038cca.cfg" />
    <None Include=".godot\editor\project_metadata.cfg" />
    <None Include=".godot\editor\recent_dirs" />
    <None Include=".godot\editor\script_editor_cache.cfg" />
    <None Include=".godot\editor\TueTue.cs-folding-4a644074e8cdd02cd2f80c3055524c92.cfg" />
    <None Include=".godot\exported\133200997\file_cache" />
    <None Include=".godot\export_credentials.cfg" />
    <None Include=".godot\global_script_class_cache.cfg" />
    <None Include=".godot\imported\big_energy.png-c638522544a8ff7d814a2060716e3568.ctex" />
    <None Include=".godot\imported\big_energy.png-c638522544a8ff7d814a2060716e3568.md5" />
    <None Include=".godot\imported\big_energy.png-dde9ba7d3f3f250847cd879d304a3813.ctex" />
    <None Include=".godot\imported\big_energy.png-dde9ba7d3f3f250847cd879d304a3813.md5" />
    <None Include=".godot\imported\character_icon_char_name.png-acafc87acacdad6bbe5c811c2eb5b6d0.ctex" />
    <None Include=".godot\imported\character_icon_char_name.png-acafc87acacdad6bbe5c811c2eb5b6d0.md5" />
    <None Include=".godot\imported\character_icon_char_name.png-c4f5cae7318c8cfa7bc3a461fc23781d.ctex" />
    <None Include=".godot\imported\character_icon_char_name.png-c4f5cae7318c8cfa7bc3a461fc23781d.md5" />
    <None Include=".godot\imported\char_select_char_name.png-55f7b1c8a13396bbf83c5f6b4e541bbc.ctex" />
    <None Include=".godot\imported\char_select_char_name.png-55f7b1c8a13396bbf83c5f6b4e541bbc.md5" />
    <None Include=".godot\imported\char_select_char_name.png-be2684834a8bd14a63fca937ac654e68.ctex" />
    <None Include=".godot\imported\char_select_char_name.png-be2684834a8bd14a63fca937ac654e68.md5" />
    <None Include=".godot\imported\char_select_char_name_locked.png-2c1bf8c9bacdd384d2d875bd6fff7bdc.ctex" />
    <None Include=".godot\imported\char_select_char_name_locked.png-2c1bf8c9bacdd384d2d875bd6fff7bdc.md5" />
    <None Include=".godot\imported\char_select_char_name_locked.png-65da5ecbe46823c7162430431adc1f21.ctex" />
    <None Include=".godot\imported\char_select_char_name_locked.png-65da5ecbe46823c7162430431adc1f21.md5" />
    <None Include=".godot\imported\icon.svg-218a8f2b3041327d8a5756f3a245f83b.ctex" />
    <None Include=".godot\imported\icon.svg-218a8f2b3041327d8a5756f3a245f83b.md5" />
    <None Include=".godot\imported\map_marker_char_name.png-6313e304b75e59e74149eedef9b21b14.ctex" />
    <None Include=".godot\imported\map_marker_char_name.png-6313e304b75e59e74149eedef9b21b14.md5" />
    <None Include=".godot\imported\map_marker_char_name.png-ac508d6821de0c29c3f530fb0411f561.ctex" />
    <None Include=".godot\imported\map_marker_char_name.png-ac508d6821de0c29c3f530fb0411f561.md5" />
    <None Include=".godot\imported\mod_image.png-04da6f2c9a74875d6490034da2a6f890.ctex" />
    <None Include=".godot\imported\mod_image.png-04da6f2c9a74875d6490034da2a6f890.md5" />
    <None Include=".godot\imported\mod_image.png-be3a333ed6fe6c63b6df124cf8b0cee6.ctex" />
    <None Include=".godot\imported\mod_image.png-be3a333ed6fe6c63b6df124cf8b0cee6.md5" />
    <None Include=".godot\imported\pancake.png-4327eea2f57a2e38ea3bd111ba5af722.ctex" />
    <None Include=".godot\imported\pancake.png-4327eea2f57a2e38ea3bd111ba5af722.md5" />
    <None Include=".godot\imported\pancake.png-99a2702ddf7c156136c50b0f29f3217a.ctex" />
    <None Include=".godot\imported\pancake.png-99a2702ddf7c156136c50b0f29f3217a.md5" />
    <None Include=".godot\imported\pat.png-1f38e696b2d3799d6bbb31ef828d40f1.ctex" />
    <None Include=".godot\imported\pat.png-1f38e696b2d3799d6bbb31ef828d40f1.md5" />
    <None Include=".godot\imported\pat.png-53ba485bde23fd39b7755c911fddbca1.ctex" />
    <None Include=".godot\imported\pat.png-53ba485bde23fd39b7755c911fddbca1.md5" />
    <None Include=".godot\imported\pat.png-65b078910b56979213e1298e7d875a3c.ctex" />
    <None Include=".godot\imported\pat.png-65b078910b56979213e1298e7d875a3c.md5" />
    <None Include=".godot\imported\pat.png-aea1f48aa54ea6dbccbcb2f4a1643ce8.ctex" />
    <None Include=".godot\imported\pat.png-aea1f48aa54ea6dbccbcb2f4a1643ce8.md5" />
    <None Include=".godot\imported\power.png-0cf28f116e20f782669e4ad17f1c8262.ctex" />
    <None Include=".godot\imported\power.png-0cf28f116e20f782669e4ad17f1c8262.md5" />
    <None Include=".godot\imported\power.png-408191f8e5326087ac31cf5a67f6a547.ctex" />
    <None Include=".godot\imported\power.png-408191f8e5326087ac31cf5a67f6a547.md5" />
    <None Include=".godot\imported\power.png-858e434454f7f382ead1df280f6fce0d.ctex" />
    <None Include=".godot\imported\power.png-858e434454f7f382ead1df280f6fce0d.md5" />
    <None Include=".godot\imported\power.png-d4eba4bc3697feef90ffe8d4f3c8fe3f.ctex" />
    <None Include=".godot\imported\power.png-d4eba4bc3697feef90ffe8d4f3c8fe3f.md5" />
    <None Include=".godot\imported\relic.png-5533bb40fd1b32610678b953965a50fb.ctex" />
    <None Include=".godot\imported\relic.png-5533bb40fd1b32610678b953965a50fb.md5" />
    <None Include=".godot\imported\relic.png-71961c349bf14f92c1b2c22f30c568f5.ctex" />
    <None Include=".godot\imported\relic.png-71961c349bf14f92c1b2c22f30c568f5.md5" />
    <None Include=".godot\imported\relic.png-76bd666bd503d11dd11a83d91b0294d9.ctex" />
    <None Include=".godot\imported\relic.png-76bd666bd503d11dd11a83d91b0294d9.md5" />
    <None Include=".godot\imported\relic.png-c26103a2e2004f139620f15481284936.ctex" />
    <None Include=".godot\imported\relic.png-c26103a2e2004f139620f15481284936.md5" />
    <None Include=".godot\imported\relic_outline.png-4cf8f439f0cb404936a7d4a7e690352f.ctex" />
    <None Include=".godot\imported\relic_outline.png-4cf8f439f0cb404936a7d4a7e690352f.md5" />
    <None Include=".godot\imported\relic_outline.png-f4d92b1004af443103229ef1d388a340.ctex" />
    <None Include=".godot\imported\relic_outline.png-f4d92b1004af443103229ef1d388a340.md5" />
    <None Include=".godot\imported\text_energy.png-6244da962ba78658d0011aaad172314a.ctex" />
    <None Include=".godot\imported\text_energy.png-6244da962ba78658d0011aaad172314a.md5" />
    <None Include=".godot\imported\text_energy.png-a2ceb4677b3b14f9ae9af0f2eb40477f.ctex" />
    <None Include=".godot\imported\text_energy.png-a2ceb4677b3b14f9ae9af0f2eb40477f.md5" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\0Harmony.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\BaseLib.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\clretwrc.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\clrgc.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\clrgcexp.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\clrjit.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\CoolCakeCook2.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\CoolCakeCook2.pdb" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\coreclr.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\createdump.exe" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\GodotSharp.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\hostfxr.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\hostpolicy.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Microsoft.CSharp.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Microsoft.DiaSymReader.Native.amd64.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Microsoft.VisualBasic.Core.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Microsoft.VisualBasic.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Microsoft.Win32.Primitives.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Microsoft.Win32.Registry.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\mscordaccore.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\mscordaccore_amd64_amd64_9.0.1526.17522.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\mscordbi.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\mscorlib.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\mscorrc.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\msquic.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\netstandard.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Sentry.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\SharpGen.Runtime.COM.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\SharpGen.Runtime.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\SmartFormat.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\SmartFormat.ZString.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Steamworks.NET.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\sts2.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.AppContext.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Buffers.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Collections.Concurrent.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Collections.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Collections.Immutable.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Collections.NonGeneric.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Collections.Specialized.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.ComponentModel.Annotations.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.ComponentModel.DataAnnotations.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.ComponentModel.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.ComponentModel.EventBasedAsync.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.ComponentModel.Primitives.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.ComponentModel.TypeConverter.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Configuration.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Console.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Core.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Data.Common.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Data.DataSetExtensions.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Data.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Diagnostics.Contracts.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Diagnostics.Debug.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Diagnostics.DiagnosticSource.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Diagnostics.FileVersionInfo.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Diagnostics.Process.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Diagnostics.StackTrace.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Diagnostics.TextWriterTraceListener.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Diagnostics.Tools.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Diagnostics.TraceSource.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Diagnostics.Tracing.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Drawing.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Drawing.Primitives.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Dynamic.Runtime.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Formats.Asn1.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Formats.Tar.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Globalization.Calendars.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Globalization.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Globalization.Extensions.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.Compression.Brotli.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.Compression.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.Compression.FileSystem.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.Compression.Native.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.Compression.ZipFile.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.FileSystem.AccessControl.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.FileSystem.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.FileSystem.DriveInfo.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.FileSystem.Primitives.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.FileSystem.Watcher.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.Hashing.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.IsolatedStorage.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.MemoryMappedFiles.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.Pipelines.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.Pipes.AccessControl.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.Pipes.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.IO.UnmanagedMemoryStream.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Linq.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Linq.Expressions.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Linq.Parallel.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Linq.Queryable.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Memory.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.Http.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.Http.Json.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.HttpListener.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.Mail.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.NameResolution.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.NetworkInformation.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.Ping.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.Primitives.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.Quic.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.Requests.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.Security.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.ServicePoint.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.Sockets.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.WebClient.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.WebHeaderCollection.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.WebProxy.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.WebSockets.Client.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Net.WebSockets.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Numerics.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Numerics.Vectors.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.ObjectModel.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Private.CoreLib.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Private.DataContractSerialization.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Private.Uri.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Private.Xml.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Private.Xml.Linq.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Reflection.DispatchProxy.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Reflection.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Reflection.Emit.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Reflection.Emit.ILGeneration.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Reflection.Emit.Lightweight.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Reflection.Extensions.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Reflection.Metadata.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Reflection.Primitives.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Reflection.TypeExtensions.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Resources.Reader.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Resources.ResourceManager.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Resources.Writer.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.CompilerServices.Unsafe.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.CompilerServices.VisualC.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.Extensions.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.Handles.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.InteropServices.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.InteropServices.JavaScript.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.InteropServices.RuntimeInformation.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.Intrinsics.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.Loader.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.Numerics.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.Serialization.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.Serialization.Formatters.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.Serialization.Json.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.Serialization.Primitives.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Runtime.Serialization.Xml.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.AccessControl.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Claims.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Cryptography.Algorithms.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Cryptography.Cng.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Cryptography.Csp.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Cryptography.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Cryptography.Encoding.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Cryptography.OpenSsl.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Cryptography.Primitives.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Cryptography.X509Certificates.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Principal.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.Principal.Windows.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Security.SecureString.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.ServiceModel.Web.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.ServiceProcess.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Text.Encoding.CodePages.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Text.Encoding.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Text.Encoding.Extensions.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Text.Encodings.Web.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Text.Json.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Text.RegularExpressions.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Threading.Channels.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Threading.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Threading.Overlapped.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Threading.Tasks.Dataflow.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Threading.Tasks.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Threading.Tasks.Extensions.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Threading.Tasks.Parallel.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Threading.Thread.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Threading.ThreadPool.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Threading.Timer.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Transactions.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Transactions.Local.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.ValueTuple.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Web.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Web.HttpUtility.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Windows.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Xml.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Xml.Linq.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Xml.ReaderWriter.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Xml.Serialization.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Xml.XDocument.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Xml.XmlDocument.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Xml.XmlSerializer.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Xml.XPath.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\System.Xml.XPath.XDocument.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Vortice.DirectX.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Vortice.DXGI.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\Vortice.Mathematics.dll" />
    <None Include=".godot\mono\temp\bin\ExportRelease\win-x64\WindowsBase.dll" />
    <None Include=".godot\mono\temp\obj\CoolCakeCook2.csproj.nuget.g.props" />
    <None Include=".godot\mono\temp\obj\CoolCakeCook2.csproj.nuget.g.targets" />
    <None Include=".godot\mono\temp\obj\Debug\CoolCakeCook2.AssemblyInfoInputs.cache" />
    <None Include=".godot\mono\temp\obj\Debug\CoolCakeCook2.assets.cache" />
    <None Include=".godot\mono\temp\obj\Debug\CoolCakeCook2.csproj.AssemblyReference.cache" />
    <None Include=".godot\mono\temp\obj\Debug\CoolCakeCook2.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCake.5447C92E.Up2Date" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.AssemblyInfoInputs.cache" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.assets.cache" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.csproj.AssemblyReference.cache" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.csproj.CoreCompileInputs.cache" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.dll" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.genruntimeconfig.cache" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\CoolCakeCook2.pdb" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\refint\CoolCakeCook2.dll" />
    <None Include=".godot\mono\temp\obj\ExportRelease\win-x64\ref\CoolCakeCook2.dll" />
    <None Include=".godot\mono\temp\obj\project.nuget.cache" />
    <None Include=".godot\shader_cache\BestFitNormalShaderRD\8c748b5176971d04b037d61fe8ee9c0da50efc42fb21ff2f4fc11dbf138ac284\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\BlitShaderRD\25c59c709fcd7c8e69780f3edeaebc055b68c06b660c69bb43d8246614325591\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\BokehDofShaderRD\5a14c722b7cad6a5d1853b764825b687b8e8c26d08a7edef6f50a28c2a237b9c\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\CanvasOcclusionShaderRD\2e1e40e085c85bd3960b7bad3be9bad88a3e02174708138d2eb3215933437ede\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\CanvasSdfShaderRD\e3e36a196484fd7752bf3d5dca5d9ff7512a4e981b5f5f57e6f0a0fc50640721\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\CanvasShaderRD\8f73ea59600218c7f4a72f38f0a825d4b9edae392f00688807259ea2faf43974\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\CanvasShaderRD\8f73ea59600218c7f4a72f38f0a825d4b9edae392f00688807259ea2faf43974\45fb1ddc6499e56682916a355ce2839e61f42dfe.vulkan.cache" />
    <None Include=".godot\shader_cache\CanvasShaderRD\8f73ea59600218c7f4a72f38f0a825d4b9edae392f00688807259ea2faf43974\8a7277c8d3ac029b087c3fa9c55de85560be5119.vulkan.cache" />
    <None Include=".godot\shader_cache\CanvasShaderRD\8f73ea59600218c7f4a72f38f0a825d4b9edae392f00688807259ea2faf43974\c0a681ae42aa3e0b5abba232ccae0b036be455e4.vulkan.cache" />
    <None Include=".godot\shader_cache\CanvasShaderRD\8f73ea59600218c7f4a72f38f0a825d4b9edae392f00688807259ea2faf43974\f3e258e8f7ec2e7e740b62f3bc48ecf5c99fb0db.vulkan.cache" />
    <None Include=".godot\shader_cache\ClusterDebugShaderRD\7253e84e6deaaf9cd1391aff49a754db31e162f9ecaf776485fde4bc31121aa6\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\ClusterRenderShaderRD\5520632edde9dc7efc467666b1888d0f07fe10e4c2e113e68f1757bab97a847b\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\ClusterStoreShaderRD\9ca626ebec243544ae7398e49713da5e69391ab29de1ced02b03e718a013c28f\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\CopyShaderRD\363226e4e754f4dd97b1000777a12a1e717a0202ef34a8bb5cbbee343880d1a3\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\CopyToFbShaderRD\0adebb67e6205ddab89bef68d0541718044b8408d301ef90fcc572ab1f1dc3c1\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\CubemapDownsamplerShaderRD\831be8c39044041b2e1da3b55ee6c2d5d5242c0c11326369eda23b7ae42ee04c\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\CubemapFilterShaderRD\73d1b21cf27dc843bbcc28dc35d902623419ae7f0c17dba1d9c725d82959f576\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\CubemapRoughnessShaderRD\bb92ea060a11d89f9121ad84bf077cdf954f39a59c3cc78038611f19f3d94533\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\CubeToDpShaderRD\f3ba78a7ce282686c1bace415c6d4852f8b5df07fd90aff0139030354b9c53e6\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\FsrUpscaleShaderRD\0715ca028e84f0a9b6f91a4ac308d37a5c185438f466e254fac8b7377dc10759\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\GiShaderRD\69ca96412569cbef4a05e515b55b5744ab10048a32a6d2fef2a7c2ad984c9155\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\GiShaderRD\e4e3882307beba471cbf1d2ebf8ca49fedccbba528ef384e7d1e2461d14a71f0\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\IntegrateDfgShaderRD\287328d7c084c243ad82ac05423c4a58662ea18582b5b369f3288be49e4a66d8\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\LuminanceReduceShaderRD\62fd065f2a03f76e82ff0efdd729b029811828e67b3dc62b0dd4c1b2a8eb2c23\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\MotionVectorsShaderRD\e9ac9ae0667a399f458196d55204937c545356cd64ba755844d9c9943cffdc55\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\ParticlesCopyShaderRD\76ee6b7648ff369a05e8340a639ce08c065370fd23e6d18634d522db1c3ac055\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\ParticlesShaderRD\c77129ff51da9b8bd8037785c1a2afcdca1f25aa602d8d22c4973640d55305a4\f128cab0b22fb7e0d9f023d6cdb81309be392d95.vulkan.cache" />
    <None Include=".godot\shader_cache\ResolveShaderRD\5e0937d6a862fc03f2a42b11dd8fcc8ca9fa948bc51bc5504f3e3a92e954cc33\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\111f8cfd3c260d918df85827eb251dc36a43cb13.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\35a078cb7dc07df55e460ed1a913486a68ab6bb0.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\3d6fc53bad5e871b1b878eb1a4ed0a0fcec449cb.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\7412c254abd0f944fb53942228920fe187f1d723.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\7a57964a6a80c226a1011fb78edbda41d2219632.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\7a6b05ba6ca90f8a542e0d1fcc3360f7d52c6e09.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\7d4c2429f20db9b651852713d31971380f209eec.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\89044bace37a3ce54cf2cc5190e11bed6d14f97a.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\a38af1e47720abf30ca44f3d3c099c07b046df81.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\ab0b960474f1491b42ef9f2ca13dbd4ccaf64911.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\f88424e725a3bb50f358e9b042552af7b1c2f921.vulkan.cache" />
    <None Include=".godot\shader_cache\SceneForwardClusteredShaderRD\df8d1dbb6fb950c04bcc78fb1667a6eb52d604ac1f0317023833936c838ed75f\f89c365b12d7e2d46fb2e1f6ace46a76b6cd5e89.vulkan.cache" />
    <None Include=".godot\shader_cache\ScreenSpaceReflectionFilterShaderRD\b8974626c582dd282d9ca1bd58b6ffeda45b41e5b160baa199088657ad7eca95\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\ScreenSpaceReflectionScaleShaderRD\f028513910f44db288a6d0d7315df152a910214dd680426d7817a0db185bb512\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\ScreenSpaceReflectionShaderRD\aa7798f702ec7502be62da736ef869c792a69bb4310d9a535e0b6596ad1c4c8f\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SdfgiDebugProbesShaderRD\c25d7a81827da688487a69637d3e61ae9f31c125940f4fbf05b6de4a2c1e78a9\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SdfgiDebugShaderRD\6de37bb5aa871af3d348d47b0cbfc09f6873bf5a2500f0cf9280e404ff4ce97b\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SdfgiDirectLightShaderRD\a3474a0b60ebab5bb7010596e49cfb91bbfc3689c4df741b809ddc92e1fa90e9\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SdfgiIntegrateShaderRD\62e2ae895bf90996b40c48aeab6a59c24d27c6c843ef9ee94adf3f6de80b26ac\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SdfgiPreprocessShaderRD\60c77a38319fd7cc123270bcc0dfbdddd8f74e985d1907c08c726e3d4dbf7b06\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\ShadowFrustumShaderRD\851c9007fbee11476e65c3cbb595c7113c7e98676c38d49b88056bdb1eb5904b\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SkeletonShaderRD\e0325885d3b45ea42d045525d1c732805f14a5a6cc4b6b67ce336626653e9573\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SkyShaderRD\9c26bd5dc001c975a8ec36520d74f1e5aa9d8125c8172a160acf52f8ebf362f3\03e3b11c69e24394b2d955a8c0ba85587bb70839.vulkan.cache" />
    <None Include=".godot\shader_cache\SkyShaderRD\9c26bd5dc001c975a8ec36520d74f1e5aa9d8125c8172a160acf52f8ebf362f3\6b847b83944af8d9a9af91a0871566e6070998ca.vulkan.cache" />
    <None Include=".godot\shader_cache\SkyShaderRD\9c26bd5dc001c975a8ec36520d74f1e5aa9d8125c8172a160acf52f8ebf362f3\de678811d1bad3cad4892a8db7b6ea0be197d51d.vulkan.cache" />
    <None Include=".godot\shader_cache\SkyShaderRD\9c26bd5dc001c975a8ec36520d74f1e5aa9d8125c8172a160acf52f8ebf362f3\e105b1e014f9523daf8d734c2f2dc115ba341902.vulkan.cache" />
    <None Include=".godot\shader_cache\SmaaBlendingShaderRD\9f3b4dcf01e8d340348bba93235fb3c9c13964b1e1bd23e7d59891cc9748a71c\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SmaaEdgeDetectionShaderRD\e4c623cbbd80f252ca1afe76f478a818c89eb124cff6ca285865b0ba733f1f07\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SmaaWeightCalculationShaderRD\604beebafad6f83aaaead58113c3a3e5b0ed7a7c5605fd197dd952e3821b5878\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SortShaderRD\ce9b4120b1d1a35c1bea19b12a6206dee2526af5e61fd4520555d6b447f15e34\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SpecularMergeShaderRD\99444119f03d2c92d5ab325e0fa261255c819d4cb4b019c0eaa369b2d0383a8f\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SsaoBlurShaderRD\4d3910b2d37af6bb5a68153677dd3f49c424b932871284ee1bb2e31936b31ca0\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SsaoImportanceMapShaderRD\fe84d24f104b577d6ae2183f611ddfa9ef6ba4834d972f00460c66aa67c6e788\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SsaoInterleaveShaderRD\b804d0579b589636ca331298d9f8885e277e5fd8be1d20d4560044000a029a49\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SsaoShaderRD\6831fded981ced729634af4cf4f5515538ff84cbb773c0d583873e29462e1080\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SsEffectsDownsampleShaderRD\47ce5b07a7399a4ea52ee0ba0ba0016f7c1b3429f72c2ef29b4382bf8f1d92e7\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SsilBlurShaderRD\9d2d3e521c5d1601e636d8fc3e533a52362ad011112fde07a344fe3511cea943\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SsilImportanceMapShaderRD\3d668b995f5f00c0cdb73fd8c13cd3bed37bf5f45c10621fcc2475eefd50a7bd\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SsilInterleaveShaderRD\36d769d4532c446edf161d4b3d932557d4fad2904fda9c5f6861ae7fd162c9ee\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SsilShaderRD\335e8f9954286db1ee28430b2c9ef17fb01fb4bb8b74d688be9cec967dee41e6\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\SubsurfaceScatteringShaderRD\cfc79a4166aa45746b6bfa4b2a3345978e68ace79a0a82ab13fdda9f32a7a0b0\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\TaaResolveShaderRD\8e863ed5b6e6cf5b67a722559308f90a5653d397bdedd8d8c2abe45a89893049\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\TonemapShaderRD\06d49e3e1e33f4e3f9069e4df65b734ffc54e7ad36b2b03be9c40766a30f7576\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\VolumetricFogProcessShaderRD\6b05211651f14a1593c8b3be3b5932c64a3beba37ce1e1649b4ea67ac36d3c47\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\VolumetricFogShaderRD\963b90021bd602c144aa8f80b75ecdf64c2abe48940f55cf2f25f2deda808186\9a227745af2d65830f930370a9fbba551fbd6f60.vulkan.cache" />
    <None Include=".godot\shader_cache\VoxelGiDebugShaderRD\49ee1e463ded1be1341dc6ee222f492cd9f8484aabe4cf39ca46f519abecbb6c\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\VoxelGiShaderRD\3d7b0b0258a2977a47dc0a84db7cb49a5e1bfaa74053e42ffae7d3e87d48965f\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\shader_cache\VrsShaderRD\c86a9b4edb92bad6f336fcaf68fd7f5e123c9317179b774d48915216f3d81819\087916079fba7c625e62b0c2cca570e0fb87c99a.vulkan.cache" />
    <None Include=".godot\uid_cache.bin" />
    <None Include="CoolCakeCook2.sln" />
    <None Include="export_presets.cfg" />
    <None Include="icon.svg" />
    <None Include="icon.svg.import" />
    <None Include="packages\CoolCakeCook2.pck" />
    <None Include="project.godot" />
    <None Include="README.md" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BaseLib">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\mods\BaseLib.3.0.6\BaseLib.dll</HintPath>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\GodotSharp.dll</HintPath>
    </Reference>
    <Reference Include="sts2">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Using Include="BaseLib" />
    <Using Include="Godot" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include=".godot\mono\temp\bin\Debug\" />
    <Folder Include=".godot\mono\temp\obj\Debug\refint\" />
    <Folder Include=".godot\mono\temp\obj\Debug\ref\" />
    <Folder Include=".godot\shader_cache\Fsr2AccumulatePassShaderRD\acf7ce56f0f217fbe6fc54b42313d025af58be39a197ea6e6a9c10b1c03de903\" />
    <Folder Include=".godot\shader_cache\Fsr2AutogenReactivePassShaderRD\ea81f3d2612452e92eebad3230c8885356cf352779194322ac0b390d949e0a9f\" />
    <Folder Include=".godot\shader_cache\Fsr2ComputeLuminancePyramidPassShaderRD\246789de2d6807e12325bb146b5b960cbec70a2119fe15f67d12c0a1d55213dd\" />
    <Folder Include=".godot\shader_cache\Fsr2DepthClipPassShaderRD\4130c931008b9d81bce5757c91876fb1c64a992525002d1a9d24c756cdaeb55f\" />
    <Folder Include=".godot\shader_cache\Fsr2LockPassShaderRD\50c95f98dbda1ad902b8fac4668d32cbfc11a3e86b890460da50600750d6d636\" />
    <Folder Include=".godot\shader_cache\Fsr2RcasPassShaderRD\3f4d394a0080ce37da6dc5f05c36e082efc8f3a0a333428f23697d21a1e665cd\" />
    <Folder Include=".godot\shader_cache\Fsr2ReconstructPreviousDepthPassShaderRD\7ef7cdf239edd510c42b9e6ef2ca760f08ac92b57c6b2e5562cf430770b69d49\" />
    <Folder Include=".godot\shader_cache\Fsr2TcrAutogenPassShaderRD\c6b965d8d141ea41ff88aa0df571ed29f4b8b5c974713f24b7fa44f23e3db020\" />
    <Folder Include=".godot\shader_cache\SceneForwardClusteredShaderRD\210d14d006d21a3471e63300f334a93a8076f61ad1c3147dbd14466d95970249\" />
    <Folder Include=".godot\shader_cache\SceneForwardClusteredShaderRD\6a184745fdc168cf1854f82e467b075c7754389099dd4260c7cfd820f974abb7\" />
    <Folder Include=".godot\shader_cache\SceneForwardClusteredShaderRD\e54e15eb9546bd2ff28fdb8fc19e33bec138fb364a5418eb6d90e784252ee190\" />
    <Folder Include=".godot\shader_cache\VolumetricFogProcessShaderRD\14fbd4a37cc30a2991dbfa525da8e6182def041c1eeaa20638fb2597e98f3c52\" />
    <Folder Include=".godot\shader_cache\VolumetricFogProcessShaderRD\2749f17fe5049db6df987d401e0fb5a52692635224ca129e06c3d6e15dd2dc29\" />
    <Folder Include=".godot\shader_cache\VolumetricFogProcessShaderRD\8333ba62fcdf5c0ffe915641fe9faa88286844b2bb245d94b41eb48eca8e881d\" />
    <Folder Include=".godot\shader_cache\VolumetricFogShaderRD\5929600387c20b3c1eead45ba7f6c87fde922e0e4f78f80366f58cdfb10e63f7\" />
    <Folder Include=".godot\shader_cache\VolumetricFogShaderRD\6120947dc0a3cd4bff5b217e63490686b128f0319aabd6f96d597268f68d60e3\" />
    <Folder Include=".godot\shader_cache\VolumetricFogShaderRD\f44655a2103d6cb3b1d0a206e66c4427aca3de3b5de59f72bf7e08db5144f83c\" />
  </ItemGroup>
</Project>