<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove=".godot\**" />
    <EmbeddedResource Remove=".godot\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="CoolCakeCook2.json" />
    <Content Include="CoolCakeCook2\localization\zhs\ancients.json" />
    <Content Include="CoolCakeCook2\localization\zhs\cards.json" />
    <Content Include="CoolCakeCook2\localization\zhs\characters.json" />
    <Content Include="CoolCakeCook2\localization\zhs\powers.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="0.1.9" />
    <AdditionalFiles Include="CoolCakeCook2/localization/**/*.json" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BaseLib">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\mods\BaseLib\BaseLib.dll</HintPath>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\GodotSharp.dll</HintPath>
    </Reference>
    <Reference Include="sts2">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Using Include="BaseLib" />
    <Using Include="Godot" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="CoolCakeCook2Code\Cards\Colorless\" />
  </ItemGroup>
</Project>