<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="CCCook2\localization\eng\**" />
    <EmbeddedResource Remove="CCCook2\localization\eng\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="CCCook2\images\card_portraits\big\pat.png" />
    <Content Include="CCCook2\images\card_portraits\pat.png" />
    <Content Include="CCCook2\images\charui\big_energy.png" />
    <Content Include="CCCook2\images\charui\character_icon_char_name.png" />
    <Content Include="CCCook2\images\charui\char_select_char_name.png" />
    <Content Include="CCCook2\images\charui\char_select_char_name_locked.png" />
    <Content Include="CCCook2\images\charui\map_marker_char_name.png" />
    <Content Include="CCCook2\images\charui\text_energy.png" />
    <Content Include="CCCook2\images\powers\big\power.png" />
    <Content Include="CCCook2\images\powers\power.png" />
    <Content Include="CCCook2\images\relics\big\relic.png" />
    <Content Include="CCCook2\images\relics\relic.png" />
    <Content Include="CCCook2\images\relics\relic_outline.png" />
    <Content Include="CCCook2\mod_image.png" />
    <Content Include="localization\zhs\cards.json" />
    <Content Include="localization\zhs\characters.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="0.1.5" />
    <AdditionalFiles Include="localization/**/*.json" />
  </ItemGroup>
  <ItemGroup>
    <None Include=".gitignore" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BaseLib">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\mods\BaseLib.3.0.6\BaseLib.dll</HintPath>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\GodotSharp.dll</HintPath>
    </Reference>
    <Reference Include="sts2">
      <HintPath>..\..\..\..\Programs\Steam\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Using Include="BaseLib" />
    <Using Include="Godot" />
  </ItemGroup>
</Project>